{
    perform: true,
    alwaysRequireAssignee: true,
    labelsRequiringAssignee: [ feature-request ],
    autoAssignees: {
        accessibility: [],
        api: [],
        css-less-sass: [],
        debug: [],
        editor: [],
        emmet: [ ramya-rao-a ],
        error-list: [],
        extensions: [],
        git: [],
        hot-exit: [],
        html: [],
        i18n: [],
        install-update: [],
        integrated-terminal: [ Tyriar ],
        javascript: [],
        json: [],
        languages basic: [],
        markdown: [],
        php: [],
        search: [],
        tasks: [],
        typescript: [],
        workbench: [],
    }
}